### ISSUE TITLE
Split ORF1ab into ORF1a and ORF1b

### ISSUE THREAD

**Issue by ivansg44** [cidgoh/COVID-MVP#125]

**Comment by anwarMZ** [comment]
ORFIab needs a more granular split now. New NSP(x) mutations in Omicron sub-variants are important to track and study. To make it easier and more informative for the user, we should explore the idea of splitting the x-axis bar into several small components. see this [Image](https://www.medrxiv.org/content/medrxiv/early/2022/05/25/2022.05.22.22275422/F1.large.jpg?width=800&height=600&carousel=1) as a template and for discussions in the coming days.

**Comment by ivansg44** [comment]
@anwarMZ Close this?
